Lego-API-MVC/Admin_MVC/Controllers/FilterOptionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models.Models;
using Roposityres.interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using USER_API.Authontaction;
using ViewModels;

namespace Admin_MVC.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class FilterOptionController : Controller
    {
        private readonly IUnitOfWork unit;
        private readonly IModelRepository<Filter> FilterRepo;
        private readonly IModelRepository<FilterOption> FilterOptionRepo;
        public FilterOptionController(IUnitOfWork _unit)
        {
            unit = _unit;
            FilterRepo = unit.GetFilterRepo();
            FilterOptionRepo = unit.GetFilterOptionRepo();
        }
        public IActionResult GetAll()
        {
            ViewBag.Filter = FilterRepo.GetAll().ToList();
            var AllFilter= FilterOptionRepo.GetAll();
            return View(AllFilter);
        }
        [HttpGet]
        public IActionResult GetById(int Id)
        {
            var item = FilterOptionRepo.GetById(Id);
            return View(item);
        }
        [HttpGet]
        public IActionResult Create()
        {
            var data = FilterRepo.GetAll();
            ViewBag.FilterList = new SelectList(data.ToList(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(FilterOptionVM filterVM)
        {
            if (ModelState.IsValid) {
                FilterOptionRepo.Add(filterVM.ToModel());
                await unit.Save();
                return RedirectToAction("GetAll");
            }

            var data = FilterRepo.GetAll();
            ViewBag.FilterList = new SelectList(data.ToList(), "Id", "Name");
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            var data = FilterRepo.GetAll();
            ViewBag.FilterList = new SelectList(data.ToList(), "Id", "Name");
            var filter = FilterOptionRepo.GetById(Id);
            return View(filter.ToVModel());

        }

        [HttpPost]
        public async Task<IActionResult> Edit(FilterOptionVM FOVM)
        {
            if (ModelState.IsValid)
            {
                FilterOptionRepo.Update(FOVM.ToModel());
                await unit.Save();
                return RedirectToAction("GetAll");
            }
            var data = FilterRepo.GetAll();
            ViewBag.FilterList = new SelectList(data.ToList(), "Id", "Name");
            return View(FOVM);
        }

        public async Task<IActionResult> Delete(int Id)
        {
            var e = FilterOptionRepo.GetById(Id);
            FilterOptionRepo.Remove(e);
            await unit.Save();
            return RedirectToAction("GetAll");
        }
    }
}

Lego-API-MVC/Admin_MVC/Views/FilterOption/Create.cshtml
@{
    ViewBag.Title = "Create Filter Option";
}
@model ViewModels.FilterOptionVM

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">@ViewBag.Title</h4>
            <form class="forms-sample" asp-controller="FilterOption" asp-action="Create" method="post">
                <div class="form-group">
                    <label asp-for="Name">Filter option Name</label>
                    <input asp-for="Name" type="text" class="form-control" placeholder="Name">
                    <span class="text-danger" asp-validation-for="Name"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FilterID">Filter</label><br />
                    <select asp-for="FilterID" asp-items="@(SelectList)ViewBag.FilterList">
                        <option value="Null">Choose Filter</option>
                    </select>
                </div>

                <button type="submit" class="btn btn-primary mr-2">Save</button>
                <a asp-controller="FilterOption" asp-action="GetAll" class="btn btn-dark">Cancel</a>
            </form>
        </div>
    </div>
</div>

Lego-API-MVC/Admin_MVC/Views/FilterOption/Edit.cshtml
@{
    ViewBag.Title = "Edit filter option";
}

@model ViewModels.FilterOptionVM


<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">@ViewBag.Title</h4>
            <form class="forms-sample" asp-controller="FilterOption" asp-action="Edit" method="post">
                <div class="form-group">
                    <label asp-for="Name">Filter Option Name</label>
                    <input asp-for="Name" type="text" class="form-control" placeholder="Name">
                    <span class="text-danger" asp-validation-for="Name"></span>
                </div>
                <div>
                    <label asp-for="FilterID">FilterOption ID</label><br />
                    <select asp-for="FilterID" asp-items="@(SelectList)ViewBag.FilterList">
                        <option value="Null">Choose Category</option>
                    </select>
                </div>

                <button type="submit" class="btn btn-primary mr-2">Save</button>
                <a asp-controller="FilterOption" asp-action="GetAll" class="btn btn-dark">Cancel</a>
            </form>
        </div>
    </div>
</div>

Lego-API-MVC/Admin_MVC/Views/FilterOption/GetAll.cshtml
@{

    ViewData["Title"] = "All FilterOption";
}

@model IQueryable<Models.Models.FilterOption>
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">@ViewBag.Title</h4>
            <div class="table-responsive">
                <table class="table table-dark">
                    <thead>
                        <tr>
                            <th> # </th>
                            <th> Filter Option name </th>
                            <th> Filter ID </th>
                        </tr>
                    </thead>
                    <tbody>
                        @{ var i = 1;}
                        @foreach (var item in Model)
                        {

                            <tr>
                                <td>@i</td>
                                <td>@item.Name</td>
                                <td>
                                    @*@(ViewBag.Filter).FirstOrDefault(f=>f.Id==@item.FilterId).Name*@
                                    @{
                                        var str = "";
                                        if (item.FilterId != null) { str = (ViewBag.Filter as List<Models.Models.Filter>).FirstOrDefault(f => f.Id == item.FilterId).Name; }
                                        else { str = "Null"; }
                                     }
                                 @str
                                </td>


                                <td><a asp-controller="FilterOption" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-success">Edit</a></td>
                                <td><a asp-controller="FilterOption" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a></td>
                                @*<td><a asp-controller="FilterOption" asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Details</a></td>*@
                            </tr>
                            i++;
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>