Lego-API-MVC/Admin_MVC/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models.Models;
using Roposityres.interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using USER_API.Authontaction;
using ViewModels;

namespace Admin_MVC.Models.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork unit;
        private readonly IModelRepository<Category> CatRepo;

        public CategoryController(IUnitOfWork _Unit)
        {
            unit = _Unit;
            CatRepo = unit.GetCategryRepo();
        }

        public IActionResult GetAll()
        {

            var data = CatRepo.GetAll().ToList();
            return View(data);
        }

        [HttpGet]
        public IActionResult GetById(int Id)
        {
            var data = CatRepo.GetById(Id);
            return View(data);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var data = CatRepo.GetAll();
            ViewBag.CategoryList = new SelectList(data.ToList(), "Id", "CatName");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CategoryVM c)
        {
            if (ModelState.IsValid)
            {
                CatRepo.Add(c.ToModel());
                await unit.Save();
                return RedirectToAction("GetAll");
            }
            var data = CatRepo.GetAll();
            ViewBag.CategoryList = new SelectList(data.ToList(), "Id", "CatName");
            return View();
        }
        [HttpGet]
        public IActionResult Edit(int Id)
        {
            var cat =  CatRepo.GetById(Id);
            var data = CatRepo.GetAll();
            ViewBag.CategoryList = new SelectList(data.ToList(), "Id", "CatName");
            return View(cat.ToViewModel());
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int Id,CategoryVM c)
        {
            if (ModelState.IsValid)
            {
                CatRepo.Update(c.ToModel());
                await unit.Save();
                return RedirectToAction("GetAll");
            }
            var data = CatRepo.GetAll();
            ViewBag.CategoryList = new SelectList(data.ToList(), "Id", "CatName");
            return View();
        }

        public async Task< IActionResult> Delete(int Id)
        {
            var e =  CatRepo.GetById(Id);
             CatRepo.Remove(e);
            await unit.Save();
            return RedirectToAction("GetAll");
        }

    }
}

Lego-API-MVC/Admin_MVC/Controllers/FilterController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models.Models;
using Roposityres.interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using USER_API.Authontaction;
using ViewModels;

namespace Admin_MVC.Models.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class FilterController : Controller
    {
        private readonly IUnitOfWork unit;
        private readonly IModelRepository<Filter> filtRepo;
        private readonly IModelRepository<FilterOption> filtOPtRepo;
        private readonly IRepositoryForMany<ProductOption> ProdOptRepo;

        public FilterController(IUnitOfWork _Unit)
        {
            unit = _Unit;
            filtRepo = unit.GetFilterRepo();
            filtOPtRepo = unit.GetFilterOptionRepo();
            ProdOptRepo = unit.GetProdOptRepo();
        }

        public IActionResult GetAll()
        {
            var data = filtRepo.GetAll();
            return View(data);
        }

        [HttpGet]
        public IActionResult GetById(int Id)
        {
            var data = filtRepo.GetById(Id);
            return View(data);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return  View();
        }
        [HttpPost]
        public async Task< IActionResult> Create(FilterVM f)
        {
            filtRepo.Add(f.ToModel());
            await unit.Save();
            return RedirectToAction("GetAll");
        }
        [HttpGet]
        public  IActionResult Edit(int Id)
        {
            var filter =  filtRepo.GetById(Id);
            return  View(filter.ToViewModel());
        }
        [HttpPost]
        public async Task< IActionResult > Edit(FilterVM f)
        {
             filtRepo .Update(f.ToModel());
             await unit .Save();
            return RedirectToAction("GetAll");
        }

        public async Task< IActionResult> Delete(int Id)
        {
            var filterOpt =  filtOPtRepo.GetAllOnly().Where(FO => FO.FilterId == Id);

            if (filterOpt != null)
            {
                    filtOPtRepo.DeleteRange(filterOpt);
            }
            var Entity =  filtRepo.GetById(Id);
              filtRepo.Remove(Entity);
             await unit.Save();
            return RedirectToAction("GetAll");
        }
    }
}

Lego-API-MVC/Admin_MVC/Views/Filter/Create.cshtml
@{
    ViewBag.Title = "Create Filter";
    //Layout = "~/Views/Layout/MainLayout.cshtml";
}

@model ViewModels.FilterVM


@*<form asp-controller="Filter" asp-action="Create" method="post" class="form-group">

        <label asp-for="Name">Filter Name</label>
        <input type="text" asp-for="Name" class="form-control" />
        <span class="text-danger" asp-validation-for="Name"></span>
        <br />


        <center>
            <input type="submit" value="Save" class="btn btn-primary" />
        </center>

    </form>

    <script src="~/jquery/jquery.min.js"></script>
    <script src="~/jquery-validate/jquery.validate.js"></script>
    <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>*@

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">@ViewBag.Title</h4>
            @*<p class="card-description"> Basic form elements </p>*@
        <form class="forms-sample" asp-controller="Filter" asp-action="Create" method="post">
            <div class="form-group">
                <label asp-for="Name">Name</label>
                <input asp-for="Name" type="text" class="form-control" placeholder="Name">
                <span class="text-danger" asp-validation-for="Name"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name_Ar">Name_Ar</label>
                <input asp-for="Name_Ar" type="text" class="form-control" placeholder="الاسم">
                <span class="text-danger" asp-validation-for="Name_Ar"></span>
            </div>
            @*<div class="form-group">
            <label for="exampleInputEmail3">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail3" placeholder="Email">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword4">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword4" placeholder="Password">
        </div>
        <div class="form-group">
            <label for="exampleSelectGender">Gender</label>
            <select class="form-control" id="exampleSelectGender">
                <option>Male</option>
                <option>Female</option>
            </select>
        </div>
        <div class="form-group">
            <label>File upload</label>
            <input type="file" name="img[]" class="file-upload-default">
            <div class="input-group col-xs-12">
                <input type="text" class="form-control file-upload-info" disabled placeholder="Upload Image">
                <span class="input-group-append">
                    <button class="file-upload-browse btn btn-primary" type="button">Upload</button>
                </span>
            </div>
        </div>
        <div class="form-group">
            <label for="exampleInputCity1">City</label>
            <input type="text" class="form-control" id="exampleInputCity1" placeholder="Location">
        </div>
        <div class="form-group">
            <label for="exampleTextarea1">Textarea</label>
            <textarea class="form-control" id="exampleTextarea1" rows="4"></textarea>
        </div>*@
            <button type="submit" class="btn btn-primary mr-2">Submit</button>
            <button class="btn btn-dark">Cancel</button>
        </form>
        </div>
    </div>
</div>

Lego-API-MVC/Admin_MVC/Views/Filter/Edit.cshtml
@{
    ViewBag.Title = "Edit Filter";
}

@model ViewModels.FilterVM




<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">@ViewBag.Title</h4>
            <form class="forms-sample" asp-controller="Filter" asp-action="Edit" method="post">
                <div class="form-group">
                    <label asp-for="Name">Name</label>
                    <input asp-for="Name" type="text" class="form-control" placeholder="Name">
                    <span class="text-danger" asp-validation-for="Name"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name_Ar">Name_Ar</label>
                    <input asp-for="Name_Ar" type="text" class="form-control" placeholder="الاسم">
                    <span class="text-danger" asp-validation-for="Name_Ar"></span>
                </div>
                <button type="submit" class="btn btn-primary mr-2">Save</button>
                <a asp-controller="Filter" asp-action="GetAll" class="btn btn-dark">Cancel</a>
            </form>
        </div>
    </div>
</div>

Lego-API-MVC/Admin_MVC/Views/Filter/GetAll.cshtml
@{
    ViewBag.Title = "All Product";
}



@model IQueryable<Models.Models.Filter>

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">@ViewBag.Title</h4>
            <div class="table-responsive">
                <table class="table table-dark">
                    <thead>
                        <tr>
                            <th> # </th>
                            <th> Filter name </th>
                        </tr>
                    </thead>
                    <tbody>
                        @{ var i = 1;}
                        @foreach (var item in  Model)
                        {

                            <tr>
                                <td>@i</td>
                                <td>@item.Name</td>

                                <td><a asp-controller="Category" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-success">Edit</a></td>
                                <td><a asp-controller="Category" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a></td>
                                @*<td><a asp-controller="Category" asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Details</a></td>*@
                            </tr>
                            i++;
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>